name: fmt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install poetry
        env:
          POETRY_VERSION: "2.0.1"
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: mypy
        run: |
          poetry run mypy pinot_connect

      - name: isort
        run: poetry run isort --check .

      - name: black
        run: poetry run black --check .