site_name: pinot-connect
nav:
  - pinot-connect: index.md
  - Learn:
      Learn: usage/index.md
      Basic Usage: usage/basic.md
      Configuration: usage/options.md
      Row Factories: usage/row_factories.md
  - Reference:
      Reference: reference/index.md
      pinot_connect.connection: reference/connection.md
      pinot_connect.cursor: reference/cursor.md
      pinot_connect.options: reference/options.md
      pinot_connect.exceptions: reference/exceptions.md
      pinot_connect.rows: reference/rows.md
      pinot_connect.context: reference/context.md
  - Benchmarks: benchmarks.md
  - Release Notes: release_notes.md

theme:
  name: 'material'
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

repo_name: zschumacher/pinot-connect
repo_url: https://github.com/zschumacher/pinot-connect

# disable edit links
edit_uri: ''

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: 🔗